[__config__]
url = "https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat"
input = "dlc.dat"
version = 2

["geolocation-!cn"]
bases = ["geolocation-!cn"]
attr_filters = ["lacks:cn", "lacks:ads"]
output = "/dev/null"

["another-!cn"]
depends = "geolocation-!cn"
bases = ["google"]
output = "ruleset/another-!cn.json"

[ai]
url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
input = "geosite.dat"
bases = ["anthropic", "xai"]
